# Generated by Django 4.0.5 on 2023-02-04 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.PositiveSmallIntegerField()),
                ('number_of_tickets', models.PositiveIntegerField()),
                ('average_resolution_time', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
